[package]
name = "datafusion-loki"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
datafusion = { workspace = true }
futures = "0.3"
parquet = { version = "55", features = ["async"] }
reqwest = { version = "0.12", features = ["stream"] }
# TODO remove this
tokio = { workspace = true, features = ["full"] }