[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = { workspace = true }
datafusion-loki = { path = "../datafusion-loki" }
datafusion-proto = { workspace = true }
tokio = { workspace = true }
